spring:
  application:
    name: parser

  datasource:
    url: jdbc:h2:mem:parserdb
    username: parser
    password: parser
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

logging:
  level:
    root: INFO

dl-output: C:\\Users\\skothur1\\Downloads\\KeYMaeraXOutput\\
chunk-size: 5